### ISSUE TITLE
Android EventEmitter wrong condition for takePending

### ISSUE THREAD

**Issue by FrenkyBojler** [urbanairship/airship-mobile-framework-proxy#43]
Hello guys,
I noticed event listeners started to behave wrong on Android and found a flawed code for getting pending events.

In PR #39 there is a commit containing this change in file `android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/events/EventEmitter.kt`

![image](https://github.com/urbanairship/airship-mobile-framework-proxy/assets/14737925/ee293da2-71ce-4c2a-a2a8-1f85d1f405ac)

The code doesn't work as expected, it removes and returns ALL of the pending events (ignoring the given types).

The code snippet should look like this:
`pendingEvents.removeAll {
       types.contains(it.type) && result.add(it)
  }`

You can check a demonstration here in Kotlin Playground: 
https://pl.kotl.in/Ae27Yxg4a

Cheers

**Comment by rlepinski** [comment]
This was fixed in 6.3.0 of this lib
